name: FluxerSRV
version: '${version}'
main: com.fluxer.srv.FluxerSRV
api-version: '1.20'
description: A custom, lightweight plugin to bridge Minecraft and Fluxer.
author: Oisann

commands:
  fluxer:
    description: Main Fluxer command
    usage: /fluxer
    permission: fluxersrv.admin
    permission-message: You do not have permission to execute this command!

permissions:
  fluxersrv.admin:
    description: Allows administrative commands for FluxerSRV.
    default: op
